# netlify.toml

[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/totalsupply"
  to = "/.netlify/functions/totalsupply"
  status = 200
  force = true

[[redirects]]
  from = "/cmc/totalsupply"
  to = "/.netlify/functions/cmc-totalsupply"
  status = 200
  force = true